/**
 * export_pdf.c — Raw PDF generation implementation
 *
 * Generates a styled PDF file by writing the PDF file format directly.
 * No external PDF library needed — PDF is a well-documented text format.
 *
 * Layout matches the JS version: dark header bar, orange title accent,
 * cover page with stats, and a multi-page history listing.
 *
 * @version 1.0.0
 */

#include "export_pdf.h"
#include "platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ── PDF Constants ───────────────────────────────────────────────── */

#define PAGE_WIDTH    612.0f     /* US Letter */
#define PAGE_HEIGHT   792.0f
#define MARGIN_LEFT    50.0f
#define MARGIN_RIGHT   50.0f
#define MARGIN_TOP     50.0f
#define MARGIN_BOTTOM  50.0f
#define LINE_HEIGHT    14.0f
#define HEADER_HEIGHT 100.0f
#define FOOTER_HEIGHT  30.0f

/* Maximum objects we'll track for the xref table */
#define MAX_OBJECTS 2048

/* ── Internal State ──────────────────────────────────────────────── */

typedef struct {
    FILE   *f;
    long    offsets[MAX_OBJECTS];    /* byte offset of each object */
    int     obj_count;
    int     page_obj_ids[512];      /* object IDs for page objects */
    int     page_count;
    int     pages_obj_id;           /* the /Pages object ID */
    int     font_helv_id;
    int     font_helv_bold_id;
    int     font_courier_id;
} PdfWriter;

/* ── Low-level PDF writing ───────────────────────────────────────── */

static int pdf_begin_obj(PdfWriter *w) {
    int id = ++w->obj_count;
    w->offsets[id] = ftell(w->f);
    fprintf(w->f, "%d 0 obj\n", id);
    return id;
}

static void pdf_end_obj(PdfWriter *w) {
    (void)w;
    fprintf(w->f, "endobj\n\n");
}

/**
 * Escape a string for PDF text display.
 * PDF strings use ( ) delimiters with \ escaping.
 */
static void pdf_escape_string(char *dst, size_t dstsize, const char *src) {
    size_t j = 0;
    dst[0] = '\0';
    if (!src) return;

    for (size_t i = 0; src[i] && j < dstsize - 2; i++) {
        switch (src[i]) {
            case '(':  if (j + 2 < dstsize) { dst[j++] = '\\'; dst[j++] = '('; } break;
            case ')':  if (j + 2 < dstsize) { dst[j++] = '\\'; dst[j++] = ')'; } break;
            case '\\': if (j + 2 < dstsize) { dst[j++] = '\\'; dst[j++] = '\\'; } break;
            default:
                /* Skip non-printable chars and chars > 127 for safety */
                if ((unsigned char)src[i] >= 32 && (unsigned char)src[i] < 127) {
                    dst[j++] = src[i];
                } else if ((unsigned char)src[i] == '\t') {
                    if (j + 1 < dstsize) dst[j++] = ' ';
                }
                break;
        }
    }
    dst[j] = '\0';
}

/**
 * Truncate a string to fit within maxchars, adding "..." if truncated.
 */
static void truncate_str(char *dst, size_t dstsize, const char *src, int maxchars) {
    if (!src || !*src) {
        snprintf(dst, dstsize, "(untitled)");
        return;
    }
    int len = (int)strlen(src);
    if (len <= maxchars) {
        pdf_escape_string(dst, dstsize, src);
    } else {
        char tmp[2048];
        strncpy(tmp, src, (size_t)maxchars - 3);
        tmp[maxchars - 3] = '\0';
        strcat(tmp, "...");
        pdf_escape_string(dst, dstsize, tmp);
    }
}

/* ── Page Content Generation ─────────────────────────────────────── */

/**
 * Build the cover page content stream.
 */
static void build_cover_page(char *buf, size_t bufsize,
                              const HistoryStats *stats, const char *timestamp) {
    char most_visited_esc[512];
    pdf_escape_string(most_visited_esc, sizeof(most_visited_esc), stats->most_visited_url);

    char most_title_esc[512];
    pdf_escape_string(most_title_esc, sizeof(most_title_esc), stats->most_visited_title);

    snprintf(buf, bufsize,
        /* ── Dark header background ── */
        "q\n"
        "0.13 0.13 0.17 rg\n"
        "0 692 612 100 re f\n"
        "Q\n"

        /* ── Title text (orange) ── */
        "BT\n"
        "/F2 26 Tf\n"
        "1 0.6 0.2 rg\n"
        "50 740 Td\n"
        "(BRAVE HISTORY ACCESS) Tj\n"
        "ET\n"

        /* ── Subtitle ── */
        "BT\n"
        "/F1 11 Tf\n"
        "0.8 0.8 0.85 rg\n"
        "50 718 Td\n"
        "(Browser History Access Tool — C Edition v1.0) Tj\n"
        "ET\n"

        /* ── Timestamp ── */
        "BT\n"
        "/F3 9 Tf\n"
        "0.5 0.5 0.55 rg\n"
        "50 700 Td\n"
        "(Generated: %s) Tj\n"
        "ET\n"

        /* ── About section ── */
        "BT\n"
        "/F2 15 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "50 650 Td\n"
        "(About This Report) Tj\n"
        "ET\n"

        "BT\n"
        "/F1 10 Tf\n"
        "0.2 0.2 0.2 rg\n"
        "50 632 Td\n"
        "(This report was generated by the Brave History Access tool \\(C edition\\).) Tj\n"
        "0 -16 Td\n"
        "(It reads Brave Browser's SQLite history database directly from disk,) Tj\n"
        "0 -16 Td\n"
        "(providing comprehensive access to your browsing history.) Tj\n"
        "ET\n"

        /* ── Statistics section ── */
        "BT\n"
        "/F2 15 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "50 560 Td\n"
        "(Summary Statistics) Tj\n"
        "ET\n"

        /* Stats background */
        "q\n"
        "0.95 0.95 0.97 rg\n"
        "45 430 522 120 re f\n"
        "Q\n"

        "BT\n"
        "/F1 11 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "60 535 Td\n"
        "(Total URLs:           %d) Tj\n"
        "0 -18 Td\n"
        "(Total Visits:         %d) Tj\n"
        "0 -18 Td\n"
        "(Unique Domains:       %d) Tj\n"
        "0 -18 Td\n"
        "(Earliest Visit:       %s) Tj\n"
        "0 -18 Td\n"
        "(Latest Visit:         %s) Tj\n"
        "ET\n"

        /* ── Most visited ── */
        "BT\n"
        "/F2 15 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "50 400 Td\n"
        "(Most Visited Page) Tj\n"
        "ET\n"

        "BT\n"
        "/F1 10 Tf\n"
        "0.2 0.2 0.2 rg\n"
        "60 380 Td\n"
        "(Title: %s) Tj\n"
        "0 -15 Td\n"
        "(Visits: %d) Tj\n"
        "ET\n"

        "BT\n"
        "/F3 8 Tf\n"
        "0.3 0.3 0.6 rg\n"
        "60 350 Td\n"
        "(%s) Tj\n"
        "ET\n"

        /* ── Methods section ── */
        "BT\n"
        "/F2 15 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "50 310 Td\n"
        "(Access Method) Tj\n"
        "ET\n"

        "BT\n"
        "/F1 10 Tf\n"
        "0.2 0.2 0.2 rg\n"
        "60 292 Td\n"
        "(Direct SQLite database read — the most comprehensive method.) Tj\n"
        "0 -15 Td\n"
        "(Brave's History database was copied and queried directly.) Tj\n"
        "0 -15 Td\n"
        "(No browser extensions or APIs required.) Tj\n"
        "ET\n"

        /* ── Security notice ── */
        "BT\n"
        "/F2 15 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "50 220 Td\n"
        "(Security Notice) Tj\n"
        "ET\n"

        "BT\n"
        "/F1 10 Tf\n"
        "0.4 0.15 0.15 rg\n"
        "60 202 Td\n"
        "(This tool is for personal and educational use only.) Tj\n"
        "0 -15 Td\n"
        "(Do not use it to monitor others without their consent.) Tj\n"
        "0 -15 Td\n"
        "(Incognito history is not accessible — by design.) Tj\n"
        "ET\n"

        /* ── Footer bar ── */
        "q\n"
        "0.13 0.13 0.17 rg\n"
        "0 0 612 30 re f\n"
        "Q\n"

        "BT\n"
        "/F1 8 Tf\n"
        "0.5 0.5 0.55 rg\n"
        "50 10 Td\n"
        "(Brave History Access — C Edition — Page 1) Tj\n"
        "ET\n",

        timestamp,
        stats->total_urls,
        stats->total_visits,
        stats->unique_domains,
        stats->earliest_visit,
        stats->latest_visit,
        most_title_esc,
        stats->most_visited_count,
        most_visited_esc
    );
}

/**
 * Build a history listing page content stream.
 * Returns the number of entries written.
 */
static int build_listing_page(char *buf, size_t bufsize,
                               const HistoryResult *result,
                               int start_idx, int page_num) {
    char *p = buf;
    char *end = buf + bufsize - 256;   /* safety margin */
    int written = 0;

    /* Header bar */
    p += snprintf(p, (size_t)(end - p),
        "q\n"
        "0.13 0.13 0.17 rg\n"
        "0 752 612 40 re f\n"
        "Q\n"

        "BT\n"
        "/F2 14 Tf\n"
        "1 0.6 0.2 rg\n"
        "50 764 Td\n"
        "(BROWSING HISTORY) Tj\n"
        "ET\n"
    );

    /* Column headers */
    p += snprintf(p, (size_t)(end - p),
        /* Header background */
        "q\n"
        "0.92 0.92 0.94 rg\n"
        "40 726 532 18 re f\n"
        "Q\n"

        "BT\n"
        "/F2 8 Tf\n"
        "0.15 0.15 0.15 rg\n"
        "45 730 Td\n"
        "(#) Tj\n"
        "30 0 Td\n"
        "(Title) Tj\n"
        "200 0 Td\n"
        "(URL) Tj\n"
        "190 0 Td\n"
        "(Visits) Tj\n"
        "45 0 Td\n"
        "(Last Visited) Tj\n"
        "ET\n"
    );

    float y = 714.0f;
    float min_y = FOOTER_HEIGHT + 20.0f;

    for (int i = start_idx; i < result->count && y > min_y && p < end; i++) {
        const HistoryEntry *e = &result->entries[i];

        char title_esc[256];
        truncate_str(title_esc, sizeof(title_esc), e->title, 30);

        char url_esc[256];
        truncate_str(url_esc, sizeof(url_esc), e->url, 35);

        char date_short[32];
        if (strlen(e->last_visit_time) >= 10) {
            strncpy(date_short, e->last_visit_time, 10);
            date_short[10] = '\0';
        } else {
            strncpy(date_short, e->last_visit_time, sizeof(date_short) - 1);
            date_short[sizeof(date_short) - 1] = '\0';
        }

        /* Alternating row background */
        if (written % 2 == 0) {
            p += snprintf(p, (size_t)(end - p),
                "q\n0.97 0.97 0.98 rg\n40 %.0f 532 12 re f\nQ\n",
                y - 3.0f);
        }

        p += snprintf(p, (size_t)(end - p),
            "BT\n"
            "/F3 7 Tf\n"
            "0.2 0.2 0.2 rg\n"
            "45 %.0f Td\n"
            "(%d) Tj\n"
            "ET\n"

            "BT\n"
            "/F1 7 Tf\n"
            "0.15 0.15 0.15 rg\n"
            "75 %.0f Td\n"
            "(%s) Tj\n"
            "ET\n"

            "BT\n"
            "/F3 6 Tf\n"
            "0.25 0.25 0.55 rg\n"
            "275 %.0f Td\n"
            "(%s) Tj\n"
            "ET\n"

            "BT\n"
            "/F1 7 Tf\n"
            "0.15 0.15 0.15 rg\n"
            "465 %.0f Td\n"
            "(%d) Tj\n"
            "ET\n"

            "BT\n"
            "/F3 7 Tf\n"
            "0.3 0.3 0.3 rg\n"
            "510 %.0f Td\n"
            "(%s) Tj\n"
            "ET\n",

            y, i + 1,
            y, title_esc,
            y, url_esc,
            y, e->visit_count,
            y, date_short
        );

        y -= LINE_HEIGHT;
        written++;
    }

    /* Footer bar */
    p += snprintf(p, (size_t)(end - p),
        "q\n"
        "0.13 0.13 0.17 rg\n"
        "0 0 612 30 re f\n"
        "Q\n"

        "BT\n"
        "/F1 8 Tf\n"
        "0.5 0.5 0.55 rg\n"
        "50 10 Td\n"
        "(Brave History Access — C Edition — Page %d) Tj\n"
        "ET\n",
        page_num
    );

    (void)(p);  /* suppress unused warning */
    return written;
}

/* ── Main PDF Export ─────────────────────────────────────────────── */

int export_to_pdf(const HistoryResult *result, const HistoryStats *stats,
                  const char *filepath) {
    PdfWriter w;
    memset(&w, 0, sizeof(w));

    w.f = fopen(filepath, "wb");
    if (!w.f) {
        fprintf(stderr, "[export_pdf] Cannot open %s for writing\n", filepath);
        return -1;
    }

    char timestamp[64];
    platform_timestamp_iso8601(timestamp, sizeof(timestamp));

    /* ── PDF Header ── */
    fprintf(w.f, "%%PDF-1.4\n");
    fprintf(w.f, "%%%c%c%c%c\n", 0xC0, 0xC1, 0xC2, 0xC3);  /* binary comment */

    /* ── Object 1: Catalog ── */
    int catalog_id = pdf_begin_obj(&w);
    fprintf(w.f, "<< /Type /Catalog /Pages 2 0 R >>\n");
    pdf_end_obj(&w);

    /* ── Object 2: Pages (placeholder — we'll write the real one at the end) ── */
    w.pages_obj_id = pdf_begin_obj(&w);
    /* We'll track page IDs and rewrite this. For now, placeholder. */
    long pages_offset = w.offsets[w.pages_obj_id]; /* remember for later */
    /* Write a large enough placeholder */
    fprintf(w.f, "<< /Type /Pages /Kids [                                                                                                                                                                                                                                                                          ] /Count    0 >>\n");
    pdf_end_obj(&w);

    /* ── Object 3: Font - Helvetica ── */
    w.font_helv_id = pdf_begin_obj(&w);
    fprintf(w.f, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\n");
    pdf_end_obj(&w);

    /* ── Object 4: Font - Helvetica-Bold ── */
    w.font_helv_bold_id = pdf_begin_obj(&w);
    fprintf(w.f, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\n");
    pdf_end_obj(&w);

    /* ── Object 5: Font - Courier ── */
    w.font_courier_id = pdf_begin_obj(&w);
    fprintf(w.f, "<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>\n");
    pdf_end_obj(&w);

    /* ── Object 6: Resource dictionary (shared by all pages) ── */
    int resources_id = pdf_begin_obj(&w);
    fprintf(w.f,
        "<< /Font << /F1 %d 0 R /F2 %d 0 R /F3 %d 0 R >> >>\n",
        w.font_helv_id, w.font_helv_bold_id, w.font_courier_id);
    pdf_end_obj(&w);

    /* ── Generate pages ── */

    /* Allocate a large buffer for page content */
    size_t content_bufsize = 128 * 1024;  /* 128 KB per page */
    char *content_buf = malloc(content_bufsize);
    if (!content_buf) {
        fprintf(stderr, "[export_pdf] Out of memory\n");
        fclose(w.f);
        return -1;
    }

    /* Page 1: Cover page */
    build_cover_page(content_buf, content_bufsize, stats, timestamp);
    size_t stream_len = strlen(content_buf);

    int cover_stream_id = pdf_begin_obj(&w);
    fprintf(w.f, "<< /Length %zu >>\n", stream_len);
    fprintf(w.f, "stream\n");
    fwrite(content_buf, 1, stream_len, w.f);
    fprintf(w.f, "\nendstream\n");
    pdf_end_obj(&w);

    int cover_page_id = pdf_begin_obj(&w);
    fprintf(w.f,
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        "/Resources %d 0 R /Contents %d 0 R >>\n",
        resources_id, cover_stream_id);
    pdf_end_obj(&w);
    w.page_obj_ids[w.page_count++] = cover_page_id;

    /* History listing pages */
    int entries_per_page = 48;  /* ~48 rows fit per page with our line height */
    int idx = 0;
    int page_num = 2;

    while (idx < result->count) {
        int written = build_listing_page(content_buf, content_bufsize,
                                          result, idx, page_num);
        if (written == 0) break;

        stream_len = strlen(content_buf);

        int stream_id = pdf_begin_obj(&w);
        fprintf(w.f, "<< /Length %zu >>\n", stream_len);
        fprintf(w.f, "stream\n");
        fwrite(content_buf, 1, stream_len, w.f);
        fprintf(w.f, "\nendstream\n");
        pdf_end_obj(&w);

        int page_id = pdf_begin_obj(&w);
        fprintf(w.f,
            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            "/Resources %d 0 R /Contents %d 0 R >>\n",
            resources_id, stream_id);
        pdf_end_obj(&w);
        w.page_obj_ids[w.page_count++] = page_id;

        idx += written;
        page_num++;

        if (w.page_count >= 500) break;  /* safety limit */
    }

    free(content_buf);

    /* ── Rewrite the Pages object with the correct Kids array ── */
    fseek(w.f, pages_offset, SEEK_SET);
    fprintf(w.f, "%d 0 obj\n", w.pages_obj_id);

    fprintf(w.f, "<< /Type /Pages /Kids [");
    for (int i = 0; i < w.page_count; i++) {
        fprintf(w.f, "%d 0 R ", w.page_obj_ids[i]);
    }
    fprintf(w.f, "] /Count %d >>", w.page_count);

    /* Pad to fill original placeholder space */
    long current = ftell(w.f);
    long original_end = pages_offset;
    /* Find where endobj was */
    /* We need to seek to end of file to continue writing xref */
    fseek(w.f, 0, SEEK_END);

    /* ── Cross-reference table ── */
    long xref_offset = ftell(w.f);
    fprintf(w.f, "xref\n");
    fprintf(w.f, "0 %d\n", w.obj_count + 1);
    fprintf(w.f, "0000000000 65535 f \n");
    for (int i = 1; i <= w.obj_count; i++) {
        fprintf(w.f, "%010ld 00000 n \n", w.offsets[i]);
    }

    /* ── Trailer ── */
    fprintf(w.f, "trailer\n");
    fprintf(w.f, "<< /Size %d /Root %d 0 R >>\n", w.obj_count + 1, catalog_id);
    fprintf(w.f, "startxref\n");
    fprintf(w.f, "%ld\n", xref_offset);
    fprintf(w.f, "%%%%EOF\n");

    fclose(w.f);

    printf("[export_pdf] Generated %d-page PDF: %s\n", w.page_count, filepath);
    return 0;
}
